### ISSUE TITLE
Publish Page

### ISSUE THREAD

**Issue by HClausing** [mantinband/amiko-dark#1]
Congratulations for this amazing work!

I would like to show you the Publish Page appearance, the profile selection isnt' visible, maybe needs some work here:

![image](https://user-images.githubusercontent.com/15158923/137594464-6b2fc656-34aa-473a-b6a0-e76d7fbc91aa.png)

**Comment by HClausing** [comment]
Thanks for fast answer @mantinband .

I've found this on Git Changes page:

![image](https://user-images.githubusercontent.com/15158923/137602734-d40596df-6496-423b-80bd-ef39c5c70a9a.png)

I'm not sure if it's wrong, but I think I need to show you.

**Comment by amichaiman** [comment]
> ![image](https://user-images.githubusercontent.com/15158923/137594464-6b2fc656-34aa-473a-b6a0-e76d7fbc91aa.png)

@HClausing I've updated the publish page to match the color theme:
![image](https://user-images.githubusercontent.com/32230393/137620194-b89ed686-6571-4a71-b3db-da331d5402ef.png)


> I've found this on Git Changes page:
> 
> ![image](https://user-images.githubusercontent.com/15158923/137602734-d40596df-6496-423b-80bd-ef39c5c70a9a.png)
> 
> I'm not sure if it's wrong, but I think I need to show you.

You mean that the git container is darker than the background?

**Comment by mantinband** [comment]
> ![image](https://user-images.githubusercontent.com/15158923/137594464-6b2fc656-34aa-473a-b6a0-e76d7fbc91aa.png)

@HClausing I've updated the publish page to match the color theme:
![image](https://user-images.githubusercontent.com/32230393/137620194-b89ed686-6571-4a71-b3db-da331d5402ef.png)


> I've found this on Git Changes page:
> 
> ![image](https://user-images.githubusercontent.com/15158923/137602734-d40596df-6496-423b-80bd-ef39c5c70a9a.png)
> 
> I'm not sure if it's wrong, but I think I need to show you.

You mean that the git container is darker than the background?

**Comment by mantinband** [comment]
Sure, thanks for finding that bug!

Regarding the Git container, I think it looks good like this 😎
